name: Michiganproperties
favicon: null
layout_spectrum: 0.8807126705069095
typography_spectrum: 0.17829092033207417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6972574121318758
  lightness: 0.4731464721262455
  saturation: 0.9877260772045702
  rhythmicContrast: 0.6618074004072696
purpose: []
